In [2]:
import numpy as np

### N-dimensional array - also known as ndarray in NumPy

In [6]:
np_arr = np.array([
                    [1, 2, 3],
                    [4, 5, 6]
                ])

### dtype is metadata and stores the data type

In [9]:
np_arr.dtype

dtype('int64')

### Shape tell how many rows and cols

In [8]:
np_arr.shape

(2, 3)

### ndim will tell the rows a.k.a. dimensions

In [10]:
np_arr.ndim

2

### 1. ndarray initialization techniques - Single Dimensional Array

In [20]:
# init numpy array with array() by a sequence (list, tuple)
list_arr = [1.7, 2, 3, 4, 5]
np_arr_1d = np.array(list_arr)
np_arr_1d

array([1.7, 2. , 3. , 4. , 5. ])

### Next check the shape which gives us a tuple and in this case it is 1-D array with 5 elements

In [21]:
np_arr_1d.shape # the output tells is that length of array is 5

(5,)

### Let's check the data type of ndarray

In [22]:
np_arr_1d.dtype

dtype('float64')

### 2. ndarray initialization techniques - Double Dimensional Array

In [13]:
data_2d = [
    [1, 2, 3],
    [4, 5, 6]
]
np_arr_2d = np.array(data_2d)
np_arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np_arr_2d.shape # the output tells us that it is a 2-D array with 2 rows and 3 columns

(2, 3)

In [ ]:
np_arr_2d.ndim # the output tells us that it is a 2-D array

2

In [31]:
np_arr_2d.dtype

dtype('int64')

### 3. Init with Zeros

In [33]:
arr_zeros = np.zeros(10)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
arr_zeros = np.zeros((3, 4)) # 3 rows and 4 columns
arr_zeros 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 4. Empty array with given dimensions

In [40]:
arr_empty = np.empty((2, 4, 3)) # 2 rows and 3 columns
arr_empty

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### arange is a method to define size of ndarray

In [9]:
arr_3 = np.arange(15)
arr_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### asarray method

In [ ]:
from_list_asarray = np.asarray(list_arr)
from_list_asarray
from_list_asarray is list_arr

False

In [19]:
from_ndarray_asarray = np.asarray(np_arr_2d)
from_ndarray_asarray.dtype
# from_ndarray_asarray is np_arr_2d

dtype('int64')

### ones_like creates same array with all 1s and shape/dtype same as input array

In [18]:
arr_from_ones_like = np.ones_like(from_ndarray_asarray)
arr_from_ones_like.dtype

dtype('int64')

In [23]:
arr_zeros_like = np.zeros_like(np_arr_1d)
arr_zeros_like

array([0., 0., 0., 0., 0.])

### astype - when float array typecasted to int then the decimal part is truncated

In [3]:
arr_4 = np.array([3.3, 5.3, 1, 9.43])
arr_4 = arr_4.astype(np.int32) # convert to int32
arr_4

array([3, 5, 1, 9], dtype=int32)

### astype - when the typecasting not possible we get ValueError

In [4]:
arr_str = np.array(["Pakistan", "is", 'Great!'])
arr_str.astype(np.float64) # this will raise ValueError because string cannot be converted to int

ValueError: could not convert string to float: 'Pakistan'